#!/bin/sh
#
# Squish a SMBR otapackage for distribution
# based on cyanogen
#

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   OUT_TARGET_HOST=linux-x86
   MD5=md5sum
else
   OUT_TARGET_HOST=darwin-x86
   MD5=md5
fi

if [ -z "$OUT" -o ! -d "$OUT" ]; then
	echo "ERROR: $0 only works with a full build environment. $OUT should exist."
	exit 1
fi

OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$LOGNAME.zip
if [ ! -f "$OTAPACKAGE" ]; then
	echo "$OTAPACKAGE doesn't exist!";
	exit 1
fi

QUIET=-q
DELETE_BINS="check_prereq recovery updater system/bin/applypatch system/bin/applypatch_static META-INF/com/google/android/update-script META-INF/com/android"


REPACK=$OUT/repack.d
printf "Sanitizing environment..."
rm -rf $REPACK
mkdir -p $REPACK
echo


# Unpack the otapackage
mkdir $REPACK/ota
(
cd $REPACK/ota
printf "Unpacking $OTAPACKAGE..."
unzip $QUIET $OTAPACKAGE
echo
)

# Fix build.prop
MODVERSION=$(sed -n -e'/ro\.modversion/s/^.*SMBR-//p' $REPACK/ota/system/build.prop)
sed -f $ANDROID_BUILD_TOP/vendor/shadow/tools/makerelease.rules -i $REPACK/ota/system/build.prop
sed "s/ro\.build\.display\.id=.*/ro.build.display.id=ShadowMOD-BR v${MODVERSION}/g" -i $REPACK/ota/system/build.prop

# Delete unnecessary binaries
( cd $REPACK/ota; echo $DELETE_BINS | xargs rm -rf; )

# Strip modules
find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded

# Inject GPS fix
printf "Injecting smali..."
(
SMALID=$OUT/smali.d
rm -rf $SMALID
mkdir -p $SMALID
cd $SMALID
unzip $QUIET $REPACK/ota/system/framework/framework.jar "classes.dex"
java -Xmx512m \
    -jar $ANDROID_BUILD_TOP/vendor/shadow/tools/smali/baksmali.jar classes.dex -o framework
cp -fr $ANDROID_BUILD_TOP/vendor/shadow/tools/smali/umts_sholes/framework/* framework
java -Xmx512m \
    -jar $ANDROID_BUILD_TOP/vendor/shadow/tools/smali/smali.jar framework -o classes.dex
zip $QUIET $REPACK/ota/system/framework/framework.jar "classes.dex"
rm -f classes.dex
unzip $QUIET $REPACK/ota/system/framework/services.jar "classes.dex"
java -Xmx512m \
    -jar $ANDROID_BUILD_TOP/vendor/shadow/tools/smali/baksmali.jar classes.dex -o services
cp -fr $ANDROID_BUILD_TOP/vendor/shadow/tools/smali/umts_sholes/services/* services
sed -i '/Location Proxy Service/,/I/ c\
    const-string v9, "Starting Location Proxy."\
\
    invoke-static {v5, v9}, Landroid/util/Slog;->i(Ljava/lang/String;Ljava/lang/String;)I\
\
    const-string v5, "locationproxy"\
\
    new-instance v9, Lcom/android/server/LocationProxyService;\
\
    invoke-direct {v9, v6}, Lcom/android/server/LocationProxyService;-><init>(Landroid/content/Context;)V\
\
    invoke-static {v5, v9}, Landroid/os/ServiceManager;->addService(Ljava/lang/String;Landroid/os/IBinder;)V' services/com/android/server/ServerThread.smali
java -Xmx512m \
    -jar $ANDROID_BUILD_TOP/vendor/shadow/tools/smali/smali.jar services -o classes.dex
zip $QUIET $REPACK/ota/system/framework/services.jar "classes.dex"
rm -rf $SMALID
)
echo

# Copy images
cp -f $OUT/boot.img $REPACK/ota
cp -f $OUT/bpsw.img $REPACK/ota
cp -f $OUT/devtree.img $REPACK/ota

# Opticharger all apks but Google's
OPTICHARGER=$ANDROID_BUILD_TOP/vendor/shadow/tools/opticharger
GAPPSEXCLUDELIST=$(cat $ANDROID_BUILD_TOP/vendor/shadow/products/googleapps.mk | grep .apk | cut -d ":" -f 1 | cut -d "/" -f 4 | sed 's/^/ -not -name /g' | tr -d '\n')

# Unpack the otapackage and opticharge all apks
(
cd $REPACK/ota/system/framework
$OPTICHARGER framework-res.apk
cd $REPACK/ota/system/app
find . -name "*.apk" $GAPPSEXCLUDELIST -exec $OPTICHARGER {} \;
)
echo

# Set output zip name
OUTFILE=$OUT/update-smbr-$MODVERSION-signed.zip

# Pack it up and sign
printf "Zipping package..."
( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
echo
printf "Signing package..."
SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
java -Xmx512m \
	-jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
	$REPACK/update.zip $OUTFILE
echo
printf "Cleaning up..."
rm -rf $REPACK
echo

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
$MD5 $img >$img.md5sum
echo
echo "Package complete: $OUTFILE"
cat $img.md5sum
echo
)

exit 0
